"""Add enhanced KB and solution models

Revision ID: 71daab99699a
Revises: 
Create Date: 2025-08-14 11:53:21.032631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71daab99699a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'L1'"))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eq_status'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_messages_ticket_time'))
        batch_op.create_foreign_key(None, 'agents', ['sender_agent_id'], ['id'])

    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_events_ticket_created', ['ticket_id', 'created_at'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('impact_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('urgency_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('requester_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_tickets_dept'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_dept'), ['department_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('requester_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('urgency_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('impact_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_events_ticket_created')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_messages_ticket_time'), ['ticket_id', 'timestamp'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eq_status'), ['status', 'created_at'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'L1'"))

    # ### end Alembic commands ###
